export default {
  ExploreBack: 'Explore',
  DetailBack: 'My content',
  Back: 'Back',
  Rank: 'Rank',
  SettingsBack: 'Settings',
  RankTab: "Message",
  HomeTab1: "All",
  HomeTab2: "Following",
  HomeText: "Explore",
  Community: "Community",
  CommunityTab1: "Message",
  CommunityTab2: "Group",
  DetailTab1: "Posts",
  DetailTab2: "About",
  DetailCreator: "creator",
  DetailNotes: "Notes",
  CommentTab: "Comment",
  CommentReply: "Reply",
  CommentSend: "Send",
  ArticleAccept: "Accept",
  MeWallet: "Wallet",
  MeProfile: "Profile",
  MeMyContent: "My content",
  MeCommunity: "Community",
  MeHistory: "History",
  MeSettings: "Settings",
  MeQuit: "Quit",
  MeBack: 'Me',
  SettingsNotification: "Notification",
  SettingsAppearance: "Appearance",
  SettingsFeedback: "Feedback",
  SettingsSupport: "Support",
  SettingsAbout: "About",
  AppearanceSystem: "System",
  AppearanceNight: "Night",
  AppearanceDay: "Day",
  AppearanceHeader: "Appearance",
  NotificationAccept: "Accept push",
  NotificationReply: "Reply",
  NotificationMessages: "Messages",
  NotificationFollow: "Follow",
  NotificationGroupPosts: "Group posts",
  NotificationNewTasks: "New tasks",
  NotificationReware: "New content",
  NotificationHeader: "Notifications",
  NotificationFollowed: "Followed",
  NotificationCompleted: "Completed",
  FeedbackTab: "Bug&Idea",
  FeedbackSave: "Save",
  ProfileEditTab: "Edit Profile",
  ProfileEditSave: "Save",
  ProfileEditAccountName: "Account Name",
  ProfileEditDisplayName: "Display Name",
  ProfileEditBio: "Bio",
  ProfileName: "Name",
  ProfileTab1: "Favorite",
  ProfileTab2: "Following",
  WalletSend: "Send",
  WalletSwap: "Swap",
  WalletReceive: "Receive",
}
