[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blockchain = "TQDy38CR1UyHnwP8eGL1tKdNjDjRRH5AdhGiUXuYqtH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nociza/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
